import "./globals.css";
import Head from "next/head";
import { Poppins } from "next/font/google";

const roboto = Poppins({
  weight: ["100", "300", "400", "500"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <head>
        <link
          rel="preload"
          href="/image/moon.png"
          as="image"
          media="(prefers-reduced-motion: no-preference)"
          imageSrcSet="/image/moon.png 1x, /image/moon@2x.png 2x"
        />
      </head> */}
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
